/**
 * bincall 1.0 server for Google Apps Script (http-b85 mode).
 * 
 * NOTE: THIS IS GENERATED BY A LARGE LANGUAGE MODEL AND IS ABSOLUTELY NOT
 * PRODUCTION-READY. USE IT AT YOUR OWN RISK.
 *
 * Deploy as a Web App (execute as "me", access "Anyone") and use the resulting
 * URL as the bincall API path, e.g.:
 *   https://script.google.com/macros/s/.../exec?method=auth&cred=...
 */

// =============================================================================
// Router – handle GET and POST
// =============================================================================

function doGet(e) {
    const method = e.parameter.method;
    switch (method) {
        case 'auth':
            return handleAuth(e);
        case 'delete-acc':
            return handleDeleteAcc(e);
        case 'dummy':
            return handleDummy();
        case 'whos-calling':
            return handleWhosCalling(e);
        case 'call-http':
            return handleCallHttp(e);
        case 'pickup-http':
            return handlePickupHttp(e);
        case 'connection-modes':
            return handleConnectionModes();
        default:
            return jsonError('unknown-method');
    }
}

function doPost(e) {
    const method = e.parameter.method;
    if (method === 'http-chunk-b85') {
        return handleHttpChunkB85(e);
    }
    return jsonError('unknown-method');
}

// =============================================================================
// Authentication helpers
// =============================================================================

/**
 * Parse a base64‑encoded cred parameter into {id, pw}.
 * Format: [1 byte idLen][UTF‑8 id][1 byte pwLen][UTF‑8 password]
 */
function parseCred(cred) {
    if (!cred) return null;
    const bytes = Utilities.base64Decode(cred);
    if (bytes.length < 2) return null;
    const idLen = bytes[0];
    if (bytes.length < 1 + idLen + 1) return null;
    const id = String.fromCharCode.apply(null, bytes.slice(1, 1 + idLen));
    const pwLen = bytes[1 + idLen];
    if (bytes.length < 2 + idLen + pwLen) return null;
    const pw = String.fromCharCode.apply(null, bytes.slice(2 + idLen, 2 + idLen + pwLen));
    return { id, pw };
}

/**
 * Authenticate using the cred parameter.
 * Returns { success: bool, userId?: string, reason?: string }.
 */
function authenticate(credParam) {
    const parsed = parseCred(credParam);
    if (!parsed) return { success: false, reason: 'invalid-cred' };
    const { id, pw } = parsed;
    const user = getUser(id);
    if (!user) return { success: false, reason: 'user-not-found' };
    if (hashPassword(pw, user.salt) !== user.hash) return { success: false, reason: 'wrong-password' };
    return { success: true, userId: id };
}

// =============================================================================
// User storage (script properties)
// =============================================================================

function getAllUsers() {
    return JSON.parse(PropertiesService.getScriptProperties().getProperty('users') || '{}');
}

function saveAllUsers(users) {
    PropertiesService.getScriptProperties().setProperty('users', JSON.stringify(users));
}

function getUser(id) {
    const users = getAllUsers();
    return users[id] || null;
}

function createUser(id, password) {
    const lock = LockService.getScriptLock();
    lock.waitLock(5000);
    const users = getAllUsers();
    if (users[id]) {
        lock.releaseLock();
        throw new Error('User already exists');
    }
    const salt = Utilities.base64Encode(
        Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, Utilities.getUuid() + Date.now())
    );
    const hash = hashPassword(password, salt);
    users[id] = { salt, hash };
    saveAllUsers(users);
    lock.releaseLock();
}

function deleteUser(id) {
    const lock = LockService.getScriptLock();
    lock.waitLock(5000);
    const users = getAllUsers();
    delete users[id];
    saveAllUsers(users);
    lock.releaseLock();
    // Terminate all active calls involving this user
    const cache = CacheService.getScriptCache();
    const allCallKeys = getAllCallKeys(); // Helper to iterate call states in cache
    allCallKeys.forEach(key => {
        const state = getCallState(parseInt(key.split('_')[1]));
        if (state && (state.caller === id || state.callee === id)) {
            state.ended = true;
            saveCallState(state);
        }
    });
}

function hashPassword(password, salt) {
    return Utilities.base64Encode(
        Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256, salt + password)
    );
}

// =============================================================================
// Validation
// =============================================================================

function validateUserId(id) {
    if (!id || id.length > 64) return false;
    return /^[a-zA-Z0-9][a-zA-Z0-9_-]{0,62}[a-zA-Z0-9]$/.test(id);
}

function validatePassword(pw) {
    if (!pw || pw.length < 10 || pw.length > 64) return false;
    return !/(.)\1{3}/.test(pw); // no more than 3 identical adjacent chars
}

// =============================================================================
// Call state (CacheService)
// =============================================================================

function getCallState(callId) {
    const str = CacheService.getScriptCache().get('call_' + callId);
    if (!str) return null;
    return JSON.parse(str, stateReviver);
}

function saveCallState(state) {
    const str = JSON.stringify(state, stateReplacer);
    CacheService.getScriptCache().put('call_' + state.callId, str, 600); // TTL 10 min
}

// Reviver / replacer for ARC4 states (S arrays) and re‑creating objects
function stateReplacer(key, value) {
    if (key === 'S' && Array.isArray(value)) return value; // keep numbers
    return value;
}
function stateReviver(key, value) {
    // No special handling needed; S is already array
    return value;
}

// Retrieve all call keys from the cache (simple scan not directly possible).
// We'll store an index list at 'call_list' with comma‑separated IDs.
function updateCallList(callId, remove) {
    const cache = CacheService.getScriptCache();
    const list = cache.get('call_list') || '';
    const ids = list ? list.split(',') : [];
    if (remove) {
        const idx = ids.indexOf(String(callId));
        if (idx > -1) ids.splice(idx, 1);
    } else {
        if (ids.indexOf(String(callId)) === -1) ids.push(String(callId));
    }
    cache.put('call_list', ids.join(','), 600);
}

function getAllCallKeys() {
    const list = CacheService.getScriptCache().get('call_list') || '';
    return list ? list.split(',').map(id => 'call_' + id) : [];
}

// =============================================================================
// ARC4 implementation
// =============================================================================

/**
 * RC4 encrypt/decrypt (symmetric).
 * @param {string|number[]|Uint8Array} data - Input data (string gets UTF‑8 encoded).
 * @param {string} key - Secret key (string gets UTF‑8 encoded).
 * @return {number[]} Byte[] – the encrypted/decrypted bytes (0‑255).
 */
function rc4Crypt(data, key) {
    // --- UTF‑8 helpers ---
    const toUtf8Bytes = (str) => {
        const blob = Utilities.newBlob('');
        blob.setDataFromString(str, 'UTF-8');
        return blob.getBytes();               // returns number[] (Byte[])
    };

    // Convert key to byte array (plain number[])
    const keyBytes = toUtf8Bytes(key);

    // Convert data to a Uint8Array (for internal use)
    let dataBytes;
    if (typeof data === 'string') {
        dataBytes = toUtf8Bytes(data);        // returns number[]
        dataBytes = new Uint8Array(dataBytes);
    } else if (data instanceof Uint8Array) {
        dataBytes = new Uint8Array(data);     // copy to avoid mutation
    } else if (Array.isArray(data)) {
        dataBytes = new Uint8Array(data);
    } else {
        throw new Error('Unsupported data type. Use string, number[] or Uint8Array.');
    }

    // --- KSA (Key Scheduling Algorithm) ---
    const S = new Uint8Array(256);
    for (let i = 0; i < 256; i++) S[i] = i;
    let j = 0;
    const keyLen = keyBytes.length;
    for (let i = 0; i < 256; i++) {
        j = (j + S[i] + keyBytes[i % keyLen]) & 0xFF;
        [S[i], S[j]] = [S[j], S[i]];
    }

    // --- PRGA (Pseudo-Random Generation Algorithm) ---
    const out = new Uint8Array(dataBytes.length);
    let i = 0;
    j = 0;
    for (let idx = 0; idx < dataBytes.length; idx++) {
        i = (i + 1) & 0xFF;
        j = (j + S[i]) & 0xFF;
        [S[i], S[j]] = [S[j], S[i]];
        const k = S[(S[i] + S[j]) & 0xFF];
        out[idx] = dataBytes[idx] ^ k;
    }

    // Convert Uint8Array → plain JS array (Apps Script Byte[])
    return Array.from(out);
}

// =============================================================================
// ZeroMQ Base‑85 (Z85)
// =============================================================================

const Z85_ALPHABET =
    '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ.-:+=^!/*?&<>()[]{}@%$#';

function z85Encode(bytes) {
    const padding = (4 - (bytes.length % 4)) % 4;
    const padded = bytes.slice();
    for (let i = 0; i < padding; i++) padded.push(0);
    let result = '';
    for (let i = 0; i < padded.length; i += 4) {
        let val =
            ((padded[i] << 24) | (padded[i + 1] << 16) | (padded[i + 2] << 8) | padded[i + 3]) >>> 0;
        let enc = '';
        for (let j = 0; j < 5; j++) {
            enc = Z85_ALPHABET[val % 85] + enc;
            val = Math.floor(val / 85);
        }
        result += enc;
    }
    return result;
}

function z85Decode(str) {
    const map = {};
    for (let i = 0; i < Z85_ALPHABET.length; i++) map[Z85_ALPHABET[i]] = i;

    const bytes = [];
    let pos = 0;
    const fullBlockLen = Math.floor(str.length / 5) * 5;

    // Full 5‑char → 4‑byte blocks
    for (let i = 0; i < fullBlockLen; i += 5) {
        let val = 0;
        for (let j = 0; j < 5; j++) {
            const idx = map[str[i + j]];
            if (idx === undefined) throw new Error('Invalid Z85 character');
            val = val * 85 + idx;
        }
        bytes.push((val >> 24) & 0xff, (val >> 16) & 0xff, (val >> 8) & 0xff, val & 0xff);
    }
    pos = fullBlockLen;

    // Partial block (1‑4 characters)
    const rem = str.length - pos;
    if (rem > 0) {
        const origTotalBytes = Math.floor(str.length * 4 / 5);
        const fullBytes = (pos / 5) * 4;
        const remainingBytes = origTotalBytes - fullBytes;  // 1,2,3
        const padBytes = 4 - remainingBytes;               // 3,2,1
        const missing = 5 - rem;                           // number of discarded Z85 chars

        // Value of the high‑order digits
        let prefixVal = 0;
        for (let j = 0; j < rem; j++) {
            const idx = map[str[pos + j]];
            if (idx === undefined) throw new Error('Invalid Z85 character');
            prefixVal = prefixVal * 85 + idx;
        }

        const base = prefixVal * Math.pow(85, missing);
        const modulus = Math.pow(256, padBytes);

        // Solve base + L ≡ 0 (mod modulus)
        const L = (modulus - (base % modulus)) % modulus;
        if (L >= Math.pow(85, missing)) {
            throw new Error('Invalid Z85 partial block');
        }
        const V = base + L;

        if (remainingBytes >= 1) bytes.push((V >> 24) & 0xff);
        if (remainingBytes >= 2) bytes.push((V >> 16) & 0xff);
        if (remainingBytes >= 3) bytes.push((V >> 8) & 0xff);
    }

    return bytes;
}

// =============================================================================
// Binary helpers
// =============================================================================

function strToUtf8Bytes(str) {
    return Utilities.newBlob(str).getBytes();
}

function byteArrayToBase64(arr) {
    // Apps Script expects Byte[] (signed, -128..127)
    var signed = arr.map(function (b) { return b > 127 ? b - 256 : b; });
    return Utilities.base64Encode(signed);
}

function base64ToByteArray(b64) {
    if (!b64) return [];
    var signed = Utilities.base64Decode(b64); // Byte[] (signed)
    return signed.map(function (b) { return b & 0xFF; }); // back to unsigned 0..255
}

function makeBinaryResponse(status, dataBytes) {
    const statusBytes = strToUtf8Bytes(status);
    const buf = [];

    buf.push((statusBytes.length >> 8) & 0xff);
    buf.push(statusBytes.length & 0xff);

    buf.push.apply(buf, statusBytes);

    const len = dataBytes.length;
    buf.push((len >> 24) & 0xff);
    buf.push((len >> 16) & 0xff);
    buf.push((len >> 8) & 0xff);
    buf.push(len & 0xff);

    buf.push.apply(buf, dataBytes);

    return buf;
}

// =============================================================================
// Unique ID & Key generators
// =============================================================================

function getNextCallId() {
    const lock = LockService.getScriptLock();
    lock.waitLock(5000);
    const props = PropertiesService.getScriptProperties();
    let id = parseInt(props.getProperty('nextCallId') || '1', 10);
    props.setProperty('nextCallId', (id + 1).toString());
    lock.releaseLock();
    return id;
}

const KEY_ADJECTIVES = [
    'pretty', 'beautiful', 'cute', 'angry', 'aggressive', 'wild', 'sad', 'happy', 'weird', 'surprised', 'excited', 'baby', 'old', 'grateful', 'tired', 'exhausted', 'hungry', 'brave', 'silly', 'clever', 'calm', 'lovely'
];
const KEY_ANIMALS = [
    'falcon', 'rabbit', 'fox', 'wolf', 'bear', 'lion', 'hawk', 'owl', 'deer', 'seal', 'panda', 'flamingo', 'duck', 'chicken', 'penguin', 'ostrich', 'bird', 'parrot', 'sheep', 'cow', 'goat', 'camel', 'fish', 'shark', 'whale', 'turtle', 'cat', 'dog', 'dolphin', 'tiger', 'eagle', 'dragon', 'phoenix', 'koala'
];

function generateKey() {
    const adj = KEY_ADJECTIVES[Math.floor(Math.random() * KEY_ADJECTIVES.length)];
    const animal = KEY_ANIMALS[Math.floor(Math.random() * KEY_ANIMALS.length)];
    const num = Math.floor(Math.random() * 10000);
    return `${adj}-${animal}-${num}`;
}

// =============================================================================
// Call creation
// =============================================================================

function createCall(caller, callee) {
    const callId = getNextCallId();
    const keyCaller = generateKey();
    const keyCallee = generateKey();
    const state = {
        callId,
        caller,
        callee,
        keyCaller,
        keyCallee,
        bufToCallee: '',
        bufToCaller: '',
        lastCaller: Date.now(),
        lastCallee: Date.now(),
        ended: false,
    };
    saveCallState(state);
    updateCallList(callId, false);
    return state;
}

function checkActiveCall(userA, userB) {
    const allKeys = getAllCallKeys();
    for (const key of allKeys) {
        const callId = parseInt(key.split('_')[1]);
        const st = getCallState(callId);
        if (
            st &&
            !st.ended &&
            ((st.caller === userA && st.callee === userB) || (st.caller === userB && st.callee === userA))
        ) {
            return true;
        }
    }
    return false;
}

// =============================================================================
// Triggers
// =============================================================================

/**
 * Time‑triggered cleanup – ends calls that have had no
 * http-chunk-b85 activity from either user for >30 seconds.
 */
function cleanupStaleCalls() {
    const now = Date.now();
    const allKeys = getAllCallKeys();
    const cache = CacheService.getScriptCache();

    allKeys.forEach(key => {
        const callId = parseInt(key.split('_')[1]);
        const state = getCallState(callId);
        if (!state || state.ended) {
            // Already ended or stale index entry – remove from index
            updateCallList(callId, true);
            return;
        }
        const lastActivity = Math.max(state.lastCaller, state.lastCallee);
        if (now - lastActivity > 30000) {
            state.ended = true;
            saveCallState(state);
            // Optionally clear buffers
            state.bufToCallee = '';
            state.bufToCaller = '';
            saveCallState(state);
        }
    });
}

// =============================================================================
// Method handlers
// =============================================================================

function handleAuth(e) {
    const parsed = parseCred(e.parameter.cred);
    if (!parsed) return json({ authResult: 'invalid-cred' });
    const { id, pw } = parsed;

    let user = getUser(id);
    if (!user) {
        // Try to create user
        if (!validateUserId(id) || !validatePassword(pw))
            return json({ authResult: 'invalid-id-or-pw' });
        try {
            createUser(id, pw);
        } catch (err) {
            return json({ authResult: 'create-failed' });
        }
        return json({ authResult: 'ok-created' });
    } else {
        // Existing user
        if (hashPassword(pw, user.salt) === user.hash) return json({ authResult: 'ok' });
        return json({ authResult: 'wrong-password' });
    }
}

function handleDeleteAcc(e) {
    const auth = authenticate(e.parameter.cred);
    if (!auth.success) return json({ authResult: auth.reason });
    deleteUser(auth.userId);
    return json({ authResult: 'ok', deleteResult: 'ok' });
}

function handleDummy() {
    const length = Math.floor(Math.random() * 991) + 10;
    const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 ';
    let text = '';
    for (let i = 0; i < length; i++) text += chars.charAt(Math.floor(Math.random() * chars.length));
    return ContentService.createTextOutput(text).setMimeType(ContentService.MimeType.TEXT);
}

function handleWhosCalling(e) {
    const auth = authenticate(e.parameter.cred);
    if (!auth.success) return json({ authResult: auth.reason });
    const userId = auth.userId;
    const cache = CacheService.getScriptCache();
    const now = Date.now();
    const calls = [];
    // Scan pending entries for this user
    const allPendingKeys = getPendingKeys(); // we'll maintain a simple index
    allPendingKeys.forEach(key => {
        const val = cache.get(key);
        if (!val) return;
        const pending = JSON.parse(val);
        if (pending.callee === userId && now - pending.timestamp < 60000) {
            calls.push({ caller: pending.caller, timestamp: pending.timestamp });
        }
    });
    return json({ authResult: 'ok', calls });
}

function handleCallHttp(e) {
    const auth = authenticate(e.parameter.cred);
    if (!auth.success) return json({ result: auth.reason });
    const caller = auth.userId;
    const peer = e.parameter.peer;
    if (!getUser(peer)) return json({ result: 'peer-not-found' });
    if (checkActiveCall(caller, peer)) return json({ result: 'already-in-call-with-peer' });

    const cache = CacheService.getScriptCache();
    const pendingKey = `pending_${peer}_${caller}`;
    cache.put(
        pendingKey,
        JSON.stringify({ caller, callee: peer, timestamp: Date.now() }),
        90
    );
    updatePendingList(pendingKey); // Track for cleanup

    const start = Date.now();
    const mapKey = `call_map_${caller}_${peer}`;
    while (Date.now() - start < 60000) {
        const mapVal = cache.get(mapKey);
        if (mapVal) {
            const callId = parseInt(mapVal);
            const state = getCallState(callId);
            if (state) {
                cache.remove(mapKey);
                cache.remove(pendingKey);
                removePendingFromList(pendingKey);
                return json({ result: `call-start#${callId}#${state.keyCaller}` });
            }
            break; // inconsistent state
        }
        Utilities.sleep(500);
    }
    cache.remove(pendingKey);
    removePendingFromList(pendingKey);
    cache.remove(mapKey);
    return json({ result: 'call-failed' });
}

function handlePickupHttp(e) {
    const auth = authenticate(e.parameter.cred);
    if (!auth.success) return json({ result: auth.reason });
    const callee = auth.userId;
    const peer = e.parameter.peer;
    if (!getUser(peer)) return json({ result: 'peer-not-found' });
    if (checkActiveCall(callee, peer)) return json({ result: 'already-in-call-with-peer' });

    const cache = CacheService.getScriptCache();
    const pendingKey = `pending_${callee}_${peer}`;
    const pendingVal = cache.get(pendingKey);
    if (!pendingVal) return json({ result: 'no-call' });

    // Consume pending
    cache.remove(pendingKey);
    removePendingFromList(pendingKey);

    const state = createCall(peer, callee); // peer is caller, callee is us
    const mapKey = `call_map_${peer}_${callee}`;
    cache.put(mapKey, state.callId.toString(), 70);

    return json({ result: `call-start#${state.callId}#${state.keyCallee}` });
}

function handleHttpChunkB85(e) {
    // Serialise all chunk requests to avoid race conditions on call state
    const lock = LockService.getScriptLock();
    lock.waitLock(30000); // up to 30 s
    try {
        const auth = authenticate(e.parameter.cred);
        if (!auth.success) return z85Text(makeBinaryResponse(auth.reason, []));

        const userId = auth.userId;
        const callId = parseInt(e.parameter['call-id']);
        const endFlag = e.parameter.end === '1';
        const state = getCallState(callId);

        if (!state || state.ended) return z85Text(makeBinaryResponse('end', []));
        if (state.caller !== userId && state.callee !== userId)
            return z85Text(makeBinaryResponse('auth-failed', []));

        const isCaller = userId === state.caller;
        const now = Date.now();

        // Update last activity
        if (isCaller) state.lastCaller = now;
        else state.lastCallee = now;

        // Activity timeout check (30 s)
        const lastCaller = state.lastCaller;
        const lastCallee = state.lastCallee;
        if (now - lastCaller > 30000 || now - lastCallee > 30000) {
            state.ended = true;
            saveCallState(state);
            return z85Text(makeBinaryResponse('end', []));
        }

        // Determine which user we are and get their ARC4 state
        const callKey = isCaller ? state.keyCaller : state.keyCallee;

        // Decrypt incoming data
        const postBody = e.postData ? e.postData.contents : '';
        if (postBody && postBody.trim()) {   // ignore whitespace-only bodies
            let dataBytes;
            try {
                dataBytes = z85Decode(postBody.trim());
            } catch (err) {
                // Invalid Z85 encoding – terminate the call
                state.ended = true;
                saveCallState(state);

                const snippet = postBody ? postBody.substring(0, 4096) : '(empty)';
                return z85Text(makeBinaryResponse('z85-decode-error:' + snippet, []));
            }
            if (dataBytes.length > 0) {
                const plain = rc4Crypt(dataBytes, callKey);
                // Append to peer's buffer
                const bufKey = isCaller ? 'bufToCallee' : 'bufToCaller';
                const existing = base64ToByteArray(state[bufKey]);
                const combined = existing.concat(plain);
                state[bufKey] = byteArrayToBase64(combined);
            }
        }

        // Encrypt outgoing data for this user
        const outBufKey = isCaller ? 'bufToCaller' : 'bufToCallee';
        const outPlain = base64ToByteArray(state[outBufKey]);
        let outEnc = [];
        if (outPlain.length > 0) {
            outEnc = rc4Crypt(outPlain, callKey);
            state[outBufKey] = '';
        }

        if (endFlag) state.ended = true;
        saveCallState(state);

        const status = state.ended ? 'end' : 'ok';
        return z85Text(makeBinaryResponse(status, outEnc));
    } finally {
        lock.releaseLock();
    }
}

function handleConnectionModes() {
    return json({ connectionModes: ['http-b85'] });
}

// =============================================================================
// Pending call index helpers (for "whos-calling" and cleanup)
// =============================================================================

function updatePendingList(key) {
    const cache = CacheService.getScriptCache();
    const list = cache.get('pending_list') || '';
    const keys = list ? list.split(',') : [];
    if (keys.indexOf(key) === -1) {
        keys.push(key);
        cache.put('pending_list', keys.join(','), 600);
    }
}

function removePendingFromList(key) {
    const cache = CacheService.getScriptCache();
    const list = cache.get('pending_list') || '';
    let keys = list ? list.split(',') : [];
    keys = keys.filter(k => k !== key);
    cache.put('pending_list', keys.join(','), 600);
}

function getPendingKeys() {
    const list = CacheService.getScriptCache().get('pending_list') || '';
    return list ? list.split(',') : [];
}

// =============================================================================
// JSON / text responses
// =============================================================================

function json(obj) {
    return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(
        ContentService.MimeType.JSON
    );
}

function z85Text(binaryArray) {
    return ContentService.createTextOutput(z85Encode(binaryArray)).setMimeType(
        ContentService.MimeType.TEXT
    );
}

function jsonError(reason) {
    return json({ error: reason });
}
