/**
 * Google Apps Script Web App that relays requests to a bincall server.
 * Preserves query string & bodies. Only supports the http-b85 connection mode.
 * 
 * NOTE: THIS IS GENERATED BY A LARGE LANGUAGE MODEL AND IS ABSOLUTELY NOT
 * PRODUCTION-READY. USE IT AT YOUR OWN RISK.
 *
 * Deploy as a Web App (execute as "me", access "Anyone") and use the resulting
 * URL as the bincall API path.
 */

// ========== UPSTREAM URL, CHANGE THIS ==========
var UPSTREAM_BASE = 'http://YOUR-BINCALL-SERVER/bincall';

// ========== HELPER ==========
function buildUpstreamUrl(queryString) {
    return UPSTREAM_BASE + (queryString ? '?' + queryString : '');
}

// ========== HANDLE GET ==========
function doGet(e) {
    var upstreamUrl = buildUpstreamUrl(e.queryString || '');

    var response = UrlFetchApp.fetch(upstreamUrl, {
        muteHttpExceptions: true,
        followRedirects: true,
        validateHttpsCertificates: false,
        escaping: false,
    });

    return ContentService.createTextOutput(response.getContentText())
        .setMimeType(ContentService.MimeType.TEXT);
}

// ========== HANDLE POST ==========
function doPost(e) {
    var upstreamUrl = buildUpstreamUrl(e.queryString || '');
    var body = e.postData ? e.postData.contents : '';

    var response = UrlFetchApp.fetch(upstreamUrl, {
        method: 'post',
        payload: body,
        contentType: 'text/plain',
        muteHttpExceptions: true,
        followRedirects: true,
        validateHttpsCertificates: false,
        escaping: false,
    });

    return ContentService.createTextOutput(response.getContentText())
        .setMimeType(ContentService.MimeType.TEXT);
}
